language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
before_install:
  - sudo apt-get update -qq
  - sudo pip install -U pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  # Deal with issue on Travis builders re: multiprocessing Queue
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests
script:
  - make test
